### ISSUE TITLE
Regression on Windows: no browser found

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#495]
<img width="797" alt="acli-missing-browser" src="https://user-images.githubusercontent.com/293478/112624936-8b33ce00-8e2e-11eb-8ac7-316619962d6f.png">

**Comment by grasmash** [comment]
Are you sure this is a regression?

**Comment by danepowell** [comment]
I don't see how this could be a regression, the browser-opening code hasn't changed in a year or more. More likely something about your local environment changed.

One of the following commands needs to be available in your local environment, can you confirm one of them exists?

- xdg-open
- open
- start

**Comment by anavarre** [comment]
IIRC 2 different customers reported this. I will try and get you this information.

**Comment by danepowell** [comment]
Assuming these commands are missing from customer environments:
- We'd need to know what shell they are running and whether any alternative command exists that we can use
- We could improve the warning message to specify which commands ACLI looked for
- We should fix the fatal error regardless; failing to open the browser shouldn't cause an error

**Comment by SophieG** [comment]
Customer is running on Windows 10, xdg-open and open are not recognized, but start opens a new command window.

**Comment by danepowell** [comment]
@SophieG I understand this is Windows 10, but do you know what shell in particular? i.e. Powershell, CMD, Cygwin, Git Bash, etc...? If `start http://example.com` opens a new browser, it should work in Acquia CLI as well.

**Comment by SophieG** [comment]
@danepowell they are using Powershell

**Comment by SophieG** [comment]
Customer has confirmed that running `start https://www.drupal.org/ ` command opens up a browser page (Chrome) for the Drupal landing page.

**Comment by danepowell** [comment]
https://github.com/acquia/cli/pull/518 should fix this, although I cannot reproduce the fatal error, nor can I imagine how that's possible on a modern release. There's no way for determineApiKey() to return a null value.

**Comment by SamFoster** [comment]
Dane 

I've replied in email to your request to test the patched phar file. Current behaviour is that it opens new cmd prompt - does not open browser. 

If I manually use 'open' and the IDE url I get the same behaviour - opens cmd window - no browser

If I manually use 'start' and the IDE url I get the expected behaviour - opens browser at the IDE page

Sam

**Comment by SamFoster** [comment]
Guys

This issue still not working AFAICT

<img width="960" alt="browser not opening with 1 10" src="https://user-images.githubusercontent.com/635728/115048608-a5af1380-9ed1-11eb-98cc-f5d2888c80ab.png">

that is of course if it is supposed to be in 1.10

Sam

**Comment by danepowell** [comment]
This will be in 1.11, not 1.10. You can see that it's not in the 1.10 release notes: https://github.com/acquia/cli/releases/tag/1.10.0
