### ISSUE TITLE
Fatal Error: Cache directory is not writable

### ISSUE THREAD

**Issue by rubenvarela** [acquia/cli#651]
PHP Fatal error: Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Cache directory is not writable: "phar:///usr/local/bin/acli/src/Command/Api/../../../var/cache". in phar:///usr/local/bin/acli/vendor/symfony/cache/Adapter/PhpArrayAdapter.php:313

A few of us with the latest release are now seeing this error come up. 

We are using it within a Lando environment using the Acquia recipe if that helps.

**Comment by grasmash** [comment]
Thanks for reporting this

I can’t think of anything off the top of my head that would cause this in the latest release. Can you confirm that prior to this, you were using the penultimate release? I ask because I see that the symphony cache package was updated In the penultimate release.

**Comment by grasmash** [comment]
@danepowell I think something went wrong in the packaging of the release phar. It doesn't seem to have warmed the services cache. It therefore tries to when `acli` is run, but it's not possible since the phar is not writable.

**Comment by grasmash** [comment]
@rubenvarela I believe this has been fixed. However, your local `acli` is in a broken state and must be replaced. 

Please re-run [the installation commands](https://docs.acquia.com/acquia-cli/install/).

**Comment by rubenvarela** [comment]
@grasmash I'm getting errors still and looking I don't see a phar on the release, https://github.com/acquia/cli/releases/tag/1.14.0

**Comment by grasmash** [comment]
Very odd. I just re-uploaded it.

**Comment by rubenvarela** [comment]
Thank you. A few of us have tested and workflows are working.

**Comment by danepowell** [comment]
Can someone tell me how to reproduce this? I tested the phar before attaching it to the release and it worked fine. I rebuilt it the same way as before in an attempt to figure out what went wrong, and it still works fine for every command I tested.

**Comment by danepowell** [comment]
Is it possible that folks affected by this were running the command in a Symfony environment where `APP_ENV` was set as an environment variable?

**Comment by rubenvarela** [comment]
@danepowell 

A basic environment in which to test this is inside `lando`. The `acquia` recipe for was one environment in which it was failing for quite a few of us. 

I'll spin up an environment now and check on the variable.

**Comment by danepowell** [comment]
Thanks! I can reproduce it now in Lando. I'm still not sure of the root cause (APP_ENV is not set) but I can at least start investigating.

**Comment by rubenvarela** [comment]
@danepowell Perfect! Was starting the docker desktop app.

Any command for us was showing it. I had previously set up the site, so it was authenticated in my case (in case that changes anything).

**Comment by danepowell** [comment]
Okay I sorted it out: https://github.com/acquia/cli/pull/656

Originally we thought it was due to Symfony somehow thinking that Lando was a `dev` environment. But that turned out to be a red herring, the problem was actually the missing API command cache. On my development machine there was a fallback cache pool at `/tmp/symfony-cache`, which is why it worked for me and no one else.
